USE [SmsService]
GO

IF OBJECT_ID('pbl.Account') IS NOT NULL
	DROP TABLE pbl.Account
GO

CREATE TABLE pbl.Account
(
	ID UNIQUEIDENTIFIER NOT NULL,
	Title NVARCHAR(256) NOT NULL,
	Domain VARCHAR(1000) NOT NULL,
	UserName VARCHAR(50) NOT NULL,
	[Password] VARCHAR(256) NOT NULL,
	Number VARCHAR(50) NOT NULL,
	[Enabled] BIT NOT NULL,
	CONSTRAINT PK_Account PRIMARY KEY CLUSTERED (ID ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON fgData 
)
GO