USE [SmsService]
GO

IF OBJECT_ID('pbl.Config') IS NOT NULL
	DROP TABLE pbl.Config
GO

CREATE TABLE pbl.Config
(
	ID UNIQUEIDENTIFIER NOT NULL,
	[Name] VARCHAR(256) NOT NULL UNIQUE,
	[Value] NVARCHAR(1000) NOT NULL,
	CONSTRAINT PK_Config PRIMARY KEY CLUSTERED (ID ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON fgData 
)
GO