USE [SmsService]
GO

IF OBJECT_ID('msg.Outgoing') IS NOT NULL
	DROP TABLE msg.Outgoing
GO

CREATE TABLE msg.Outgoing
(
	ID UNIQUEIDENTIFIER NOT NULL,
	SourceAccountID UNIQUEIDENTIFIER NOT NULL,
	MessageID BIGINT NOT NULL,
	[Priority] TINYINT NOT NULL, --1,2,4,8
	SendType TINYINT NOT NULL, -- 0,1,2,3
	EncodingType TINYINT NOT NULL, -- 0,1,2,5,6
	[Status] SMALLINT NOT NULL DEFAULT(0), -- 0,1,2,8,16
	ReceiverNumber VARCHAR(50) NOT NULL,
	SendDate DATETIME NOT NULL,
	DeliveryDate DATETIME NULL,
	UDH VARCHAR(50) NULL,
	Content NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_Outgoing PRIMARY KEY CLUSTERED (ID ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	
)ON fgData TEXTIMAGE_ON [fgCLOB]
GO

ALTER TABLE msg.Outgoing
	ADD CONSTRAINT FK_Outgoing_Account
	FOREIGN KEY(SourceAccountID) REFERENCES pbl.Account (ID)
GO